Add missing env requirement
https://pypi.org/project/env/

Traceback (most recent call last):
  File "/home/drjaska/defraglive/src/bot.py", line 5, in <module>
    import config
  File "/home/drjaska/defraglive/src/config.py", line 3, in <module>
    from env import environ
ModuleNotFoundError: No module named 'env'